FROM golang:1.8-alpine
ARG project_name
ENV CGO_ENABLED 0
ENV GOOS linux
EXPOSE 8080

RUN apk add --no-cache --update make git mercurial bash

RUN mkdir -p $GOPATH/src/github.com/alexbt/${project_name}
ADD . $GOPATH/src/github.com/alexbt/${project_name}
WORKDIR $GOPATH/src/github.com/alexbt/${project_name}

RUN make all

