FROM alpine:3.5
ARG bin_name
ENV rt_bin_name=${bin_name}
ENV CGO_ENABLED 0
ENV GOOS linux
ENV GOPATH=/go
ENV PATH=$PATH:$GOPATH/bin

EXPOSE 8080

WORKDIR /tmp
ADD ./${bin_name} ./
RUN chmod 777 ./${bin_name}

ENTRYPOINT /tmp/${rt_bin_name}
